### PR TITLE
Lighten up

### PR DESCRIPTION
**Pull request by andreaslarsen**
Using Merriweather 300 for body text and 400 for links and buttons and 700 for h's and stuff. No more 900.
This is obviously a personal preference so only pull if you think it looks better.

### CODE REVIEW

**Comment by davelab6** [comment]
sounds good!

**Comment by adrientetar** [comment]
Please, never ever go under 400 for body text.

ugh

Gotta say thanks to Apple for starting this 'trend' as usual...

**Comment by davelab6** [comment]
Agree that light on grey isn't good, but light on white might be ok?

**Comment by andreaslarsen** [comment]
Wow...I didn't know Merriweather 300 rendered that bad in any browser - does increasing contrast, as Dave suggested. help?

**Comment by adrientetar** [comment]
It's a 80 DPI screen. But it's not good to use light text for body anyway as it strains the eye.

Increasing contrast does not improve situation and actually makes the content more flashing. 
Google says it themselves: http://www.google.com/design/spec/style/typography.html#typography-other-typographic-guidelines

So really I showed how it renders rather badly of my computer but it's not the gist of the issue in itself, in my opinion.

**Comment by andreaslarsen** [comment]
What google says is not to use white on black which I completely agree with - the current design is grey on grey so we could still increase the contrast quite a bit and still be below 87% but if it doesn't help then it's no use. 

How about using 18px for bodytext instead - does that help?

Otherwise we can switch back and use the antialiasing hacks for mac webkit browsers

**Comment by andreaslarsen** [comment]
switched back to 400 and antialias hacked it on mac in #50

**Comment by adrientetar** [comment]
Thanks

**Pull request merged**
