### PR TITLE
Lighten up

### PR DESCRIPTION
**Pull request by andreaslarsen**
windows

### CODE REVIEW

**Comment by andreaslarsen** [comment]
this is a quick hack fix but I felt the old website was a bit too dark and uninviting so I tried to brigthen it up a bit + trim the frontpage + footer a bit

**Comment by andreaslarsen** [comment]
wide

**Comment by davelab6** [comment]
Looks awesome!

**Comment by davelab6** [comment]
I think this is a good idea to use 1 logo everywhere

**Comment by andreaslarsen** [comment]
yeah, and also just one logo on the page;) instead of 3 I think it was. Can @adrientetar confirm that text looks good on windows (my virtual box is not currently working) - I'm pretty sure I only made text bigger + increased contrast but not sure.

**Comment by andreaslarsen** [comment]
@davelab6 note that I removed the section about the mailing list - is it still being used or?

**Comment by pathumego** [comment]
@andreaslarsen Can we use the Mac icon as the logo?

**Comment by davelab6** [comment]
The mailing list gets very very little traffic. The discussions all moved to emails you can subscribe to by going to "watch on github". This should be mentioned somewhere up front.

**Comment by davelab6** [comment]
I did this for the metapolator FAQ:

> #### How can I contribute to the project?﻿
>
> We'd love to hear from you about what you do and don't like about the project.
Introduce yourself in the [Metapolator G+ Community](https://plus.google.com/communities/110027004108709154749) and let us know how you'd like to contribute.
You can also support the project financially by [buying a T shirt](http://teespring.com/metapolator-beta-0-3-0) or sending a donation.
> 
> We develop on Github, because it offers [_social coding_](https://help.github.com/articles/be-social/). If you'd like to get more involved in our development discussions, you can set Github to email you and you can reply via email too. At [github.com/metapolator/metapolator](http://github.com/metapolator/metapolator) simply set the `Watch` status on:
> 
> Watch Metapolator on Github

**Comment by andreaslarsen** [comment]
@pathumego the reason it's only mac icon is because some people had strong feelings against moving away from the U+1F4A9-esque icon currently used on win+linux

**Comment by JoesCat** [comment]
On May 9, 2015 11:58:34 AM Andreas Larsen wrote:
> yeah, would make sense just to kill the mailing lists all together. We
> could mention the github watch feature somewhere (not front page) but I
> have a feeling most potential watchers know about the feature in github
> already:)

When things work, people don't send messages. No news is good news. :-)
When things don't work, that's when the noise gets cranked-up. :-(

Older FontForge versions still point to the mailing lists, plus there are 
archives of info that might be useful, so killing a mailing list isn't a 
good idea.

Changing for the sake of change is probably a poor choice.

Introducing a new vector is better if still keeping the old avenue open.
...like growing branches on a tree vs a single wheat stalk. Stronger 
branches grow, while a single stalk is all-or-nothing (do or die).:

**Comment by andreaslarsen** [comment]
sorry, should have been more precise - I'm obviously not thinking of deleting it - but rather to point to github instead as @davelab6 suggested :)

**Comment by davelab6** [comment]
> We could mention the github watch feature somewhere (not front page) but I have a feeling most potential watchers know about the feature in github already:)

Actually a LOT of Crafitng Type people have not yet heard of github.

**Pull request merged**
