### PR TITLE
Update windows.md

### PR DESCRIPTION
**Pull request by davelab6**
This headline seems to be a much more common search term, so will be better for users

### CODE REVIEW

**Comment by adrientetar** [comment]
That's cheap.

**Comment by davelab6** [comment]
Its how the general public are searching for fontforge, but
https://www.google.co.uk/search?q=fontforge%20windows%20free%20download
doesn't return this page as the first result

**Comment by andreaslarsen** [comment]
Do we have analytics on the website so we can see what people are searching for? The title should be whatever the most common search term is - cheap/cheesy or not :)

**Comment by adrientetar** [comment]
But then you can add keywords.

**Comment by davelab6** [comment]
I think on reflection I agree with Adrien, would be better to not do this, as I did it a cheap way and when I redid it, the results didn't show that string as used so highly.

Here's the method:

screen shot 2015-05-07 at 5 57 50 pm
screen shot 2015-05-07 at 5 57 20 pm
screen shot 2015-05-07 at 5 57 42 pm
screen shot 2015-05-07 at 5 57 30 pm
screen shot 2015-05-07 at 5 57 12 pm
screen shot 2015-05-07 at 5 57 37 pm
screen shot 2015-05-07 at 5 57 58 pm

**Comment by andreaslarsen** [comment]
ok, remember to be in private/incognito when doing stuff like that - otherwise it'll be based on your google profile :)

**Comment by andreaslarsen** [comment]
@adrientetar I'm no SEO expert but I'm pretty sure keywords doesn't really do anything anymore in terms of search ranking - so your keywords has to be in the title + preferably repeated a couple of times in the text too (I now this issue is closed - just an "educative" comment). Read more e.g. http://searchenginewatch.com/sew/how-to/2390744/are-keywords-relevant-to-seo-in-2015

**Comment by davelab6** [comment]
I agree with Andreas about keywords fwif :)

**Pull request closed without merging**
