### PR TITLE
favicon update

### PR DESCRIPTION
**Pull request by andreaslarsen**
ping @davelab6

### CODE REVIEW

**Comment by davelab6** [comment]
No `.ico` file?

**Comment by andreaslarsen** [comment]
nah...clutters the home folder and much easier just to use png's unless we have to support very very very old browsers, or?

**Comment by davelab6** [comment]
MSIE 10 still requires it!  http://en.wikipedia.org/wiki/Favicon#Legacy

**Comment by andreaslarsen** [comment]
Ah...I thought it was ie7... :) 
does it have to be in the root too?

**Comment by davelab6** [comment]
Yes

**Comment by andreaslarsen** [comment]
:cry:

**Comment by andreaslarsen** [comment]
@davelab6 https://github.com/fontforge/fontforge.github.io/commit/83d0482f2758294f2bedab947a67bac3bc0b6fac

**Pull request merged**
