### PR TITLE
Trimmed the install instructions - felt they were too bloated and made t...

### PR DESCRIPTION
**Pull request by andreaslarsen**
...he whole process seem a lot more complicated than it needed to.

### CODE REVIEW

**Comment by davelab6** [comment]
I think we can do both, as this was requested by newbie users at a ct
workshop.

Put your text first, then a link to jQuery reveal more

**Comment by andreaslarsen** [comment]
Yeah, I made the assumption that users wanting to install FontForge were more familiar with how apps are installed on mac. 
Let us just leave the pull hanging for a while. 

Who's responsible for making them .dmg's?

**Comment by davelab6** [comment]
@monkeyiq runs them on his laptop and ftps them to his server and then i
post one near a release to the github issue

**Comment by andreaslarsen** [comment]
Ok, I made a simple shell command that @monkeyiq can click to create dmg's like this:

screen shot 2015-04-22 at 10 58 11

Where should I put it?

**Comment by davelab6** [comment]
In ff repo, osx directory

**Comment by andreaslarsen** [comment]
yes, figured that out by looking around - made a branch for it and assigned him there :smile:

**Pull request closed without merging**
