### PR TITLE
Update with new documentation

### PR DESCRIPTION
**Pull request by jtanx**
Same as #143, but this should work this time.

The issue with #143 is that Sphinx has directories with underscores, which Jekyll ignores by default, The initial approach I went with, which works locally, but apparently not when run under GH pages, is to add the docs directly to the `_site` folder and add `keep_files: ["docs"]` to the _config.yml. 

This approach changes that to have the docs folder outside of the _site directory (as normal), and to add:

```yml
include:
  - _static
  - _images
```

To the config.yml. This seems to work locally, and also seems to work on github pages (test site: https://fftesting.github.io)

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
Nice :-)

Let's wait for the release to merge it like you planned.

**Comment by skef** [comment]
There is still the problem of the other side of the help facility. Installations that don't have local copies will attempt to load `fontforge.sf.net` links which (I believe, and have just tested) redirect to here. 

If the new documentation files maintain the same target/`id` strings that can be handled with redirects either on this site or at the `fontforge.sf.net` server. If they don't it might be better just to leave the old documentation.

I doubt that breaking any old installation that lacks local copies is the best answer.

**Comment by jtanx** [comment]
The documentation is still there, just moved. There comes a point in time when you just have to make breaking changes.

**Comment by skef** [comment]
So to be clear, @jtanx, you advocate that older installations without local copies should get 404s now?

**Comment by jtanx** [comment]
Yes. For the best part of a couple of years, it was broken anyway, due to the domain name issues. It's not entirely all that hard to just look it up again to find what you're after.

**Pull request merged**
