### PR TITLE
Lighten up

### PR DESCRIPTION
**Pull request by andreaslarsen**
unknown-2

### CODE REVIEW

**Comment by andreaslarsen** [comment]
unknown

**Comment by andreaslarsen** [comment]
@davelab6 any reason for this not to be merged yet?

**Comment by pathumego** [comment]
why green!! Glyphs app is also green :P

**Comment by andreaslarsen** [comment]
can be any color we want...as long as it's less mess...maybe the blue tones that we'll be using for the default app theme soon anyway?

**Comment by andreaslarsen** [comment]
screen shot 2015-05-26 at 15 34 06

@pathumego

**Comment by davelab6** [comment]
Aww I commission that animation :) 

I think yellow could be nice - no other editor is using it, and the old GWW era UI was grey/yellow :D

**Comment by andreaslarsen** [comment]
hehe...random animations, video backgrounds, over the top parallax effects only serve one purpose. To create a "wow" effect to impress your client(s)...

they distract from the content and should (almost) always be avoided :wink:

**Comment by pathumego** [comment]
But Since Glypher Studio is also blue, maybe it makes sense to keep the blue. The open source font editor colour (Birdfont is blue too http://birdfont.org/)

But Im ok with yellow. But a bit brighter. I feel the existing pattern is more welcoming than what you have posted. Maybe a little brighter :)

**Comment by kosalaya** [comment]
why change the colour? existing site looks cooler to me :)

**Comment by davelab6** [comment]
If we want to remove the animation, then perhaps a plain block of color is more suitable for the 'flat' theme :)

**Comment by davelab6** [comment]
> hehe...random animations, video backgrounds, over the top parallax effects only serve one purpose. To create a "wow" effect to impress your client(s)...

I'm happy for you to decide and merge this. I think the animation was a fun little detail to add some vitality and life into the page, conveying that the fontforge project is not dead :)

**Comment by andreaslarsen** [comment]
@davelab6 yeah, I'd also prefer something more minimal - I'll try a few things.
@kosalaya because it's a font editor and not a "candy crush" app and the colors should reflect that :wink:

**Comment by davelab6** [comment]
I think font editors should be more like candy crush games :) type design should be fun!! :)

**Comment by andreaslarsen** [comment]
true - but I think we agree that fontforge is never going to be one of those editors...not in it's current form at least

**Comment by andreaslarsen** [comment]
So I'm trying to make it inviting but less toy-like :smile:

**Comment by davelab6** [comment]
hehe :) all good

**Comment by andreaslarsen** [comment]
Any thoughts on this: 

website

**Comment by andreaslarsen** [comment]
website

Now with shadow around it...

**Comment by andreaslarsen** [comment]
screen shot 2015-05-26 at 17 22 59

Green bar

**Comment by davelab6** [comment]
I think the button is a but muted in the last one

I feel strongly about avoiding the phrase 'open source,' I much prefer libre

**Comment by davelab6** [comment]
the numbers in black are a bit too dark...

**Comment by davelab6** [comment]
I think the screenshot could even becomes closer to full page-content width, no hero text required

**Comment by andreaslarsen** [comment]
hehe...open source vs libre - I get the historical and slight idiological difference (which I prefer)...problem is a lot of users don't know what libre is so you end up having to explain it which isn't what you want to do on a frontpage but let's just remove the hero text altogether and not discuss that ;)

**Comment by pathumego** [comment]
@andreaslarsen I think we could add a section about the libre nature of the project. And where will the language selector be?

And I present to you a small side project that i did Just for reference, under construction - http://mooniak.com/libre-design-tools/en/fontforge/

**Comment by pathumego** [comment]
And i think we should actually have this in a more appealing way
`FontForge is libre licensed and organized as an open source community project, so you are invited to contribute. `

**Comment by davelab6** [comment]
> a lot of users don't know what libre is so you end up having to explain it which isn't what you want to do on a frontpage 

I think a dotted underline and a http://www.w3schools.com/bootstrap/bootstrap_popover.asp with an explanation would be fine ;)

> let's just remove the hero text altogether and not discuss that ;)

;)

**Comment by andreaslarsen** [comment]
@pathumego A complete redesign could be great but I'm not sure you're heading in the right direction. It looks too much like a marketing site with big typography and icons. Reminds me too much of http://tiffzhang.com/startup/
People visiting a website like FontForge come there primarily for download and/or information. Not to be persuaded.

**Comment by pathumego** [comment]
@andreaslarsen agreed. I was referring it for the full width screenshots.

On a different note. What I made is totally a marketing website :) And no we don't have to go in that direction, I made that website because of my general dissatisfaction with most of the Libre Design tool websites. None of the websites actually 'sell' me the software properly. The recent redesign of http://www.scribus.net/ is a fine balance in that context I think. And where you are taking the website, I totally agree.

 And I don't think a bit of persuasion would hurt. After all FontForge has competition :)

**Comment by pathumego** [comment]
@andreaslarsen Oh and in case you miss understood, it is not a website for FF, its a directory of Libre Design Tools :)

**Comment by andreaslarsen** [comment]
ah, sorry - I thought it was as a replacement for the current website :+1:

**Comment by andreaslarsen** [comment]
About the language button I think we removed it since it's only in english? If/when the website gets translated it should be done similar to how we do it on designwithfontforge where we show which languages are available so instead of potentially disappointing viewers (click to see if "my" language is there...no it wasn't) it just becomes a nice feature for those who prefer the translations. Button = bad. List of available languages = good.

Full with hero image (but no animation or auto changing images or carousel or anything distracting flashy...I feel just as strongly against that as dave does "open source" or vegans do meat :neckbeard:

website

**Comment by davelab6** [comment]
lol

I like this a lot :)

**Comment by davelab6** [comment]
Given how huge proportion of users are on Windows, maybe a Windows
screenshot is better. Or a subtle fade transition from Win/Mac/Ubuntu
default window manager themes? :)

**Comment by andreaslarsen** [comment]
well technically it isn't even mac UI since I've removed most of the chrome...will try to make it even more generic/platform agnostic...

**Comment by andreaslarsen** [comment]
Chromeless
website

**Comment by davelab6** [comment]
It looks a bit strange but ok :) Maybe reduce the amount of blue margin at the top?

**Comment by andreaslarsen** [comment]
Yeah...maybe better completely stripped:
website

**Comment by andreaslarsen** [comment]
and yes, there is too much blue - this is just a mock so haven't adjusted any metrics :)

**Comment by davelab6** [comment]
Great work!! BTW The body text line length is too long, without the roundel
to keep is short :)

**Comment by andreaslarsen** [comment]
hehe...I knew you'd spot that "missing" roundel...let me just try something

**Comment by pathumego** [comment]
+1

**Comment by andreaslarsen** [comment]
I don't like the roundel - the wording is just a draft. I'm trying to keep it short and precise

fontforge open source font editor 20150526

**Comment by pathumego** [comment]
No Download numbers? I think it should be there. 

I think the libre nature of the project should be emphasised, along with the 'Free' as in beer nature.  And the roundel, was doing that

**Comment by andreaslarsen** [comment]
Download numbers are there - forgot to delay the screenshot :)

**Comment by andreaslarsen** [comment]
I think the libre get's more emphasised with a separate heading like this than shouting "FREE!" which to most users simply = "this doesn't cost me anything"

**Comment by andreaslarsen** [comment]
The roundel was just bad design (disrupted the page flow), shouting (CAPS LOCK SHOULD BE CRIMINAL!) and had an unnecessary second link to the download page.

fontforge open source font editor 20150526

**Comment by davelab6** [comment]
Looks awesome!

s/Google/a web search

**Comment by andreaslarsen** [comment]
@davelab6 thanks, not sure why there are merge conflicts - can you figure that out? 

s/Google/a ?

**Comment by davelab6** [comment]
is it ready to merge?

**Comment by davelab6** [comment]
I suggest to replace `Google` with `a web search`

**Comment by andreaslarsen** [comment]
ah...regex reference...got it...

**Comment by andreaslarsen** [comment]
Readiness to merge depends...I like this better. I know it looks more like stock bootstrap but that can also be a plus because users can find it easier to navigate.

fontforge open source font editor 20150526

**Comment by andreaslarsen** [comment]
install fontforge on mac os x 20150526 a
fontforge open source font editor 20150526

**Comment by davelab6** [comment]
I like the orange buttons on blue, and the dark grey footer.

The orange fat link underline is nice too.

I suggest adding back a fat color border to the 4 masthead links, but maybe
on the bottom edge like Material Design?

**Comment by andreaslarsen** [comment]
should be ready now

**Comment by andreaslarsen** [comment]
not sure about the masthead links - they look lacking when just showing white-on-white borderless screenshots but I think it looks better in the browser "frame"

screen shot 2015-05-26 at 23 54 53

**Comment by davelab6** [comment]
Maybe border on hover, as in Material Design?

**Comment by andreaslarsen** [comment]
can't be done easily since the padding is added to `a` element....whoever did this website didn't really think about tweak-ability or good css code in general... :) 

screen shot 2015-05-27 at 10 29 55

**Comment by andreaslarsen** [comment]
I tried making the font a little bit bigger in the nav instead:

fontforge open source font editor 20150527

**Comment by pathumego** [comment]
@andreaslarsen Nice! I feel the footer is a bit too strong. 

But do you think we need a Intro text? in your face telling its a Font Editor? We removed the hero because of the whole Libre/Open Source thing ryt?

And is copy finalised? or draft? Can we make it `Free and Open Source` font editor?

**Comment by pathumego** [comment]
@andreaslarsen and do you think making twitter logo also black / not colord is better? Since we are using like really close colour to twitter logo on the top..

**Comment by andreaslarsen** [comment]
nothing is final, I'll try adjusting the footer a bit, don't think we need intro text (users don't accidentally dump into this website and the image gives it away if they didn't already know), monochrome social is a good idea.

**Comment by andreaslarsen** [comment]
fontforge open source font editor 20150527

**Comment by andreaslarsen** [comment]
making the footer much lighter reduces the contrast too much I think

**Comment by pathumego** [comment]
@andreaslarsen Oki this is cool :dancers:

**Comment by andreaslarsen** [comment]
cheers, can we merge it now? Makes it easier to do the rest of the housecleaning

**Comment by pathumego** [comment]
:+1:  @davelab6

**Comment by pathumego** [comment]
Why cant we merge auto?

**Comment by andreaslarsen** [comment]
sure, I just thought we had a policy of not merging our own pr's but you can do it ;)

**Comment by andreaslarsen** [comment]
I'll resolve the conflict and merge now

**Comment by pathumego** [comment]
Sorry, was at dinner.. :+1:

**Comment by andreaslarsen** [comment]
no worries, was easier for me to fix the conflict since it was my mess

**Pull request closed without merging**
