### PR TITLE
Webpage cleanup

### PR DESCRIPTION
**Pull request by larsenwork**
see commits for details

### CODE REVIEW

**Comment by larsenwork** [comment]
@davelab6

**Comment by larsenwork** [comment]
I haven't deleted any files even though it might look like it - they have just been moved to `/assets/old` - I tried updating all the references along the way but I may have missed one or two but I've also fixed many broken ones so...

A couple of pointers: I've tried cleaning up in the number of scripts used (e.g. removed 6-7 from the front page) but please check `includes/html-end.html` as I've moved a couple of scripts I'm pretty sure we aren't using anywhere.

I've completely removed the sub nav pills as many of them were broken + they seemed superfluous to me.

**Comment by davelab6** [comment]
Please don't block on me! :D I think what you're doing is great, full steam
ahead!

I wish that we wouldn't 404 anyone's links, but if you want to plough
ahead, its okay

**Comment by larsenwork** [comment]
Cheers, this shouldn't be 404 anything (I've only moved 1 or 2 html files) - it's just the images and other resources that are moved.
We don't use these two scripts for anything, do we? 
https://github.com/fontforge/fontforge.github.io/blob/webpage-cleanup/_includes/html-end.html#L15-L16

**Comment by davelab6** [comment]
Gumroad was for selling prebuild packages, can be removed. Dont know about
UI, probably can go

**Comment by larsenwork** [comment]
ok, what about the math plugin? Used to display math equations but do we do that anywhere?

**Comment by davelab6** [comment]
Dont think s

**Comment by michal-n** [comment]
What about http://fontforge.github.io/en-US/documentation/developers/pfaeditmath/ ?

**Comment by larsenwork** [comment]
@michal-n nice catch - I'm assuming that's the only page?
I'll update img links too

**Comment by larsenwork** [comment]
@michal-n and @davelab - did this ever display correctly on the "old" new site?

I'm wondering because if you look in the md file it uses asterisks to wrap the math lines but those are italics in markdown and mathjax uses `$$` as default. 

I've tried fixing one of the functions here: https://github.com/fontforge/fontforge.github.io/pull/84/files#diff-f74d4e3ea5727c1182dfbef3b5c3107cR33

I think the rest would have to be fixed the same way

**Pull request merged**
